### ISSUE TITLE
Compilation error on npm run dev

### ISSUE THREAD

**Issue by wilsonsergio2500** [Toilal/vue-webpack-template#7] opened 2017-04-02 04:28 UTC
Yellow, I went thru the vue-cli installer, and when I do npm run dev.. I get Failed to compile, these dependencies were not found -- ./src/App.html?style=./App.css. What am I missing?

**Comment by Toilal** [comment] 2017-04-02 06:26
Have you run `npm install` ?

**Comment by delaneyj** [comment] 2017-04-02 16:26
Looks like the template is missing **vue-template-loader**
@wilsonsergio2500  try doing 
`npm --save-dev  vue-template-loader`
or
`yarn add --dev vue-template-loader`

With that I'm able to run here on a Win10x64 box

**Comment by wilsonsergio2500** [comment] 2017-04-02 16:48
Thank you guys, I did had value-template-loader installed. However, It must had been something related to the style loader, because once I removed style from the import it worked.. When I removed say: style=./App.css and I  only had import WithRender from "./App.html"; this worked.. In our project we are going to have all styles globalized, so for now I am good to go.. Although I will like to understand what happen..

**Comment by Toilal** [comment] 2017-04-02 16:56
Can you paste the content of App.css ?

**Comment by wilsonsergio2500** [comment] 2017-04-02 17:00
Yeah it is the default. 
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}

**Comment by Toilal** [comment] 2017-04-02 17:01
Ok, so which answers did you give when generating ? All defaults ?

**Comment by wilsonsergio2500** [comment] 2017-04-02 17:03
Yes, that is correct, option 1 all across

**Comment by ghost** [comment] 2017-04-02 17:50
I had encounter the same error, I'm sure I did installed vue-template-loader.

If I remove ?style=./app.css, everything work well.
How strange.

**Comment by Toilal** [comment] 2017-04-03 07:11
I can't reproduce the issue. Could you all give more context information ?

- OS + version
- NodeJS version
- npm or yarn version

I'm running Ubuntu 16.10, node 6.10.1, yarn 0.21.3

**Comment by Toilal** [comment] 2017-04-03 07:15
Maybe this match this windows issue : https://github.com/ktsn/vue-template-loader/issues/25

Please make sure vue-template-loader is installed with latest version (`0.3.0`)

**Comment by delaneyj** [comment] 2017-04-03 15:42
I could not get the template to work out of the gate with Win10, but adding `vue-template-loader` fixed it with no other changes.

**Comment by Toilal** [comment] 2017-04-03 15:47
I can't understand, this dependency is already in `package.json`. The only thing that could make sense is the windows issue linked in my previous comment, and calling `yarn add --dev vue-template-loader` just downloaded the fixed version (0.3.0).

When you install the template from scratch, which version of `vue-template-loader` is lying in `node_modules` directory ? If you try again from scratch, is the issue still there ?

**Comment by wilsonsergio2500** [comment] 2017-04-04 13:42
It was defaulting to Version 0.2.4, I am on Win10 also. Thanks for your help :-)

**Comment by Toilal** [comment] 2017-04-04 14:10
Ok ! Let's close this one then :)

**Closed as completed by Toilal** 2017-04-04 14:10 UTC
