### ISSUE TITLE
Using yarn results in an error

### ISSUE THREAD

**Issue by MartinSGill** [Toilal/vue-webpack-template#56] opened 2017-12-19 12:51 UTC
```
# Installing project dependencies ...
# ========================


events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Using develop template: `vue init Toilal/vue-webpack-template#develop`

**Comment by Toilal** [comment] 2017-12-19 12:58
Do you have yarn globally installed ? Does the problem occurs also with official webpack template ?

**Comment by MartinSGill** [comment] 2017-12-19 13:23
Yes and no.

* I'm on Windows so yarn is installed using the MSI they provide, and it's global (or at least, in the path) `C:\Program Files (x86)\Yarn\bin\yarn.cmd`
* It works correctly when using the webpack template.

**Comment by Toilal** [comment] 2017-12-19 13:29
If you choose to install dependencies manually (last choice) ? Everything is working properly when you run yarn manually ? It's strange it does work with official template because this part is exactly the same here.

**Comment by MartinSGill** [comment] 2017-12-19 13:39
Running yarn manually is fine, even after that error. (after cd into project folder)

**Comment by Toilal** [comment] 2018-01-10 15:02
I can reproduce this issue, but it's fixed when merging the develop branch of official template.

**Comment by Toilal** [comment] 2018-01-15 11:32
Fixed in develop branch

**Closed as completed by Toilal** 2018-01-15 11:32 UTC
